name: Build image (manual)

env:
  REGISTRY: ghcr.io

on:
  workflow_dispatch:
    inputs:
      image:
        type: choice
        required: true
        description: Image
        options: 
        - geoserver
        - geoserver_data
        - nginx
        - postgis
        - letsencrypt
      tag:
        required: true
        description: Image tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: ./docker/${{ github.event.inputs.image }}/Dockerfile
        context: "./docker/${{ github.event.inputs.image }}/"
        tags: ghcr.io/ninanor/geonode_${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}
        push: true
    - name: Final message
      run: echo "Built ${{ github.event.inputs.image }} from branch ${{ github.event.inputs.branch }}"
